# Generated by Django 3.2.4 on 2023-01-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_agronome',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_normal',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('Rancher', 'Rancher'), ('Trader', 'Trader')], default='staff', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Agronome', 'Agronome'), ('Admin', 'Admin')], default='Normal', max_length=200),
        ),
    ]
