# Generated by Django 3.2.4 on 2023-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230109_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Try other Number (startwith  +250)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone1',
            field=models.CharField(blank=True, help_text='Example +2507XXXXXXXXXXX', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone2',
            field=models.CharField(blank=True, help_text='Example +2507XXXXXXXXXXX', max_length=10, null=True),
        ),
    ]
