# Generated by Django 3.2.4 on 2023-01-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230110_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
