# Generated by Django 3.2.4 on 2023-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nid',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
