# Generated by Django 3.2.4 on 2022-12-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Messages/'),
        ),
    ]
