# Generated by Django 3.2.4 on 2022-12-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_training_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['completed']},
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='Messages/'),
        ),
    ]
