# Generated by Django 3.2.4 on 2022-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221209_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.CharField(choices=[('Farmer', 'Farmer or Rancher'), ('Buyer', 'Merchant')], default='Ibirayi', max_length=200),
        ),
    ]
