# Generated by Django 3.2.4 on 2022-12-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='short_intro',
        ),
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('Rancher', 'Rancher'), ('Trader', 'Trader')], default='Farmer', max_length=200),
        ),
    ]
