# Generated by Django 3.2.4 on 2022-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221211_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='Messages/'),
        ),
    ]
