# Generated by Django 3.2.4 on 2022-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, default='certificates/certificate.png', null=True, upload_to='Messages/'),
        ),
    ]
