# Generated by Django 3.2.4 on 2022-12-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
