# Generated by Django 3.2.4 on 2023-01-06 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20221217_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('productName', models.CharField(default='Ibirayi', max_length=200, null=True)),
                ('measurement', models.CharField(blank=True, choices=[('Kg', 'Kilograms'), ('Lt', 'Litres'), ('Tray', 'Trays'), ('Species', 'Species')], default='Kg', max_length=200, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unity',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.singleproduct'),
        ),
    ]
