# Generated by Django 3.2.4 on 2023-01-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unity',
            field=models.CharField(blank=True, choices=[('Kg', 'Kilograms'), ('Lt', 'Litres'), ('Tray', 'Trays'), ('Species', 'Species')], default='Kg', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(choices=[('Tea', 'Icyayi'), ('Coffee', 'Ikawa'), ('Cassava', 'Imyumbati'), ('Sweet Potato', 'Ibijumba'), ('Irish Potato', 'Ibirayi'), ('Maize', 'Ibigori'), ('Beans', 'Ibishyimbo')], default='Ibirayi', max_length=200),
        ),
    ]
