# Generated by Django 3.2.4 on 2023-01-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20230107_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleproduct',
            options={'verbose_name_plural': 'Single Product'},
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
