# Generated by Django 3.2.4 on 2023-01-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='productName',
        ),
    ]
