# Generated by Django 3.2.4 on 2023-01-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20230108_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quantity Purchased'),
        ),
    ]
