# Generated by Django 3.2.4 on 2023-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payments',
            field=models.ManyToManyField(blank=True, default='In Hand', to='products.Payment'),
        ),
    ]
