# Generated by Django 3.2.4 on 2023-01-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-vote_ratio', '-vote_total', '-created']},
        ),
    ]
