# Generated by Django 3.2.4 on 2023-01-09 08:18

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Try other Number (startwith  +250)', max_length=31, null=True, unique=True),
        ),
    ]
