# Generated by Django 3.2.4 on 2023-01-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_inquiry_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['is_read', '-status', '-created']},
        ),
    ]
