# Generated by Django 3.2.4 on 2023-01-15 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('productName', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Initial Price')),
                ('status', models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=200, null=True)),
                ('unity', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity Purchased')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('instock', models.BooleanField(blank=True, default=True, null=True)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-vote_ratio', '-vote_total', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('name', models.CharField(blank=True, default='Ibirayi', max_length=200, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('unity', models.CharField(blank=True, default='Kilogram', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Single Product',
            },
        ),
    ]
