# Generated by Django 3.2.4 on 2022-11-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('Tea', 'Icyayi'), ('Coffee', 'Ikawa'), ('Cassava', 'Imyumbati'), ('Sweet Potato', 'Ibijiumba'), ('Irish Potato', 'Ibirayi'), ('Maize', 'Ibigori'), ('Beans', 'Ibishyimbo')], default='Ibirayi', max_length=200),
        ),
    ]
