# Generated by Django 3.2.4 on 2022-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221112_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productType',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(choices=[('Tea', 'Icyayi'), ('Coffee', 'Ikawa'), ('Cassava', 'Imyumbati'), ('Sweet Potato', 'Ibijiumba'), ('Irish Potato', 'Ibirayi'), ('Maize', 'Ibigori'), ('Beans', 'Ibishyimbo')], default='Ibirayi', max_length=200),
        ),
    ]
