# Generated by Django 3.2.4 on 2023-01-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, max_length=200, null=True, verbose_name='Initial Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, max_length=200, null=True, verbose_name='Quantity Purchased'),
        ),
    ]
