# Generated by Django 3.2.4 on 2023-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ProductId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
