# Generated by Django 3.2.4 on 2022-12-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221210_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(choices=[('Tea', 'Icyayi'), ('Coffee', 'Ikawa'), ('Cassava', 'Imyumbati'), ('Sweet Potato', 'Ibijumba'), ('Irish Potato', 'Ibirayi'), ('Maize', 'Ibigori'), ('Beans', 'Ibishyimbo')], default='Ibirayi', max_length=200),
        ),
    ]
