# Generated by Django 3.2.4 on 2023-01-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230120_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleproduct',
            options={'verbose_name_plural': 'Category'},
        ),
    ]
