# Generated by Django 3.2.4 on 2022-12-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20221210_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unity',
            field=models.CharField(blank=True, choices=[('Kg', 'Kilograms'), ('Lt', 'Litres'), ('Tray', 'Trays'), ('Species', 'Species')], default='Kg', max_length=200, null=True),
        ),
    ]
