# Generated by Django 3.2.4 on 2022-12-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_unity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Payment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='payments',
            field=models.ManyToManyField(blank=True, to='products.Payment'),
        ),
    ]
