# Generated by Django 3.2.4 on 2023-01-07 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230106_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('name', models.CharField(blank=True, default='Ibirayi', max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=0, max_length=200, null=True)),
                ('unity', models.CharField(blank=True, default='Kilogram', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-vote_ratio', '-vote_total', 'name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='Ibirayi', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unity',
            field=models.CharField(blank=True, default='Kg', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.singleproduct'),
        ),
    ]
