# Generated by Django 3.2.4 on 2023-01-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_name_order_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], max_length=200, null=True),
        ),
    ]
