# Generated by Django 3.2.4 on 2023-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Decline', 'Decline'), ('Pending', 'Pending')], default='Pending', max_length=200, null=True),
        ),
    ]
