# Generated by Django 3.2.4 on 2023-01-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Initial Price'),
        ),
    ]
