# Generated by Django 3.2.4 on 2023-01-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20230108_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reply',
            new_name='response',
        ),
    ]
