# Generated by Django 3.2.4 on 2023-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rename_reply_order_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
